version: '3.8'

services:
  api:
    image: dockerize-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - app-data:/app
      - /app/node_modules

volumes:
  app-data: